name: Cleanup PR Preview

# Clean up preview when PR is closed
on:
  pull_request:
    types: [closed]

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Remove PR preview
      run: |
        # Configure git
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Remove preview directory for this PR
        PR_PREVIEW_DIR="preview/pr-${{ github.event.pull_request.number }}"
        if [ -d "$PR_PREVIEW_DIR" ]; then
          rm -rf "$PR_PREVIEW_DIR"
          git add .
          git commit -m "Clean up preview for closed PR #${{ github.event.pull_request.number }}"
          git push origin gh-pages
        else
          echo "Preview directory $PR_PREVIEW_DIR does not exist, nothing to clean up"
        fi